CREATE TABLE climber (
	id INT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	surname VARCHAR(255) NOT NULL,
	address VARCHAR(255) NOT NULL);
CREATE sequence CLIMBER_ID_SEQ;

CREATE TABLE country (
	id INT PRIMARY KEY,
	country_name VARCHAR(255) NOT NULL);
CREATE sequence COUNTRY_ID_SEQ;

CREATE TABLE mountain_range (
	id INT PRIMARY KEY,
	name VARCHAR(255) NOT NULL);
CREATE sequence MOUNTAIN_RANGE_ID_SEQ;

CREATE TABLE peak (
	id INT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	height FLOAT NOT NULL,
	country_id INT NOT NULL,
	mountain_range_id INT NOT NULL,
	FOREIGN KEY (country_id) REFERENCES country(id) ON DELETE CASCADE,
	FOREIGN KEY (mountain_range_id) REFERENCES mountain_range(id) ON DELETE CASCADE);
CREATE sequence PEAK_ID_SEQ;

CREATE TABLE climbing (
	id INT PRIMARY KEY,
	start_date DATE NOT NULL,
	end_date DATE,
	peak_id INT NOT NULL,
	FOREIGN KEY (peak_id) REFERENCES peak(id) ON DELETE CASCADE);
CREATE sequence CLIMBING_ID_SEQ;

CREATE TABLE climbing_group (
	id INT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	climbing_id INT NOT NULL,
	FOREIGN KEY (climbing_id) REFERENCES climbing(id) ON DELETE CASCADE);
CREATE sequence CLIMBING_GROUP_ID_SEQ;

CREATE TABLE climber_group (
	id INT PRIMARY KEY,
	climber_id INT NOT NULL,
	group_id INT NOT NULL,
	FOREIGN KEY (climber_id) REFERENCES climber(id) ON DELETE CASCADE,
	FOREIGN KEY (group_id) REFERENCES climbing_group(id) ON DELETE CASCADE);
CREATE sequence CLIMBER_GROUP_ID_SEQ;
